---
    - name: install phpmyadmin rpm from remote repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Install phpmyadmin
      yum:
        name: phpmyadmin
        state: present

    - name: Install php
      yum:
        name: php
        state: present

    - name: Configure phpMyAdmin
      template:
        src: ../templates/phpMyAdmin.conf.j2
        dest: /etc/nginx/conf.d/phpmyadmin.conf
